name: dco
on:
  pull_request:
  workflow_dispatch:

jobs:
  dco:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - run: echo "The name of your branch is ${{ github.ref }} and your event ${{ github.actor}} is ${{ github.org }}."
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: DCO Check
        uses: tim-actions/dco@v1.1.0
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
